[build]
  command = "composer install && php artisan build"
  publish = "public"

[build.environment]
  PHP_VERSION = "7.4"

[context.production.environment]
  APP_ENV = "production"
  APP_KEY = "<YOUR_APP_KEY>"
  DB_HOST = "127.0.0.1"
  DB_DATABASE = "portofolio"
  DB_USERNAME = "postgres"
  DB_PASSWORD = "12345678"
